### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by iGetUploaded** [6nz/python-loader-example#1]
So I'm new to KeyAuth with python.. But when I run the main.py I enter a name and password and then it says "username not found" and I checked the auth.json and it shows both username and password in there. Not sure what I'm doing wrong

**Comment by 6nz** [comment]
Hello, did you register an account on keyauth?

**Comment by 6nz** [comment]
This python example doesn't have a register tab

**Comment by 6nz** [comment]
This means u have to register the user manually on keyauth.win

**Comment by 6nz** [comment]
Might make a register option so u dont have to register the user manually

**Comment by iGetUploaded** [comment]
ah okay that makes sense now I didn't know I had to manually register them thanks

**Comment by 6nz** [comment]
np

**Comment by iGetUploaded** [comment]
> Might make a register option so u dont have to register the user manually

This would be dope as well

**Comment by 6nz** [comment]
Making it rn

**Comment by 6nz** [comment]
**Preview:**
![image](https://user-images.githubusercontent.com/74118308/166070775-c208e765-199c-403a-802d-d51f84e28eb8.png)

**Comment by 6nz** [comment]
oh ye and added tooltips

**Comment by iGetUploaded** [comment]
Oh wow thats dope
