### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by samogost** [6nz/python-loader-example#4]
When I run main.py, it shows cmd and disappears immediately.

**Comment by 6nz** [comment]
Run the file from cmd to see the error

**Comment by 6nz** [comment]
Or debug it somehow

**Comment by 6nz** [comment]
Cant really help without any error log

**Comment by samogost** [comment]
> Cant really help without any error log

yo

**Comment by samogost** [comment]
> Cant really help without any error log

How to convert Python to exe and merge modules so that the victim does not need to download modules when it opens

**Comment by 6nz** [comment]
Dm me on discord Marci#0101

**Comment by samogost** [comment]
> Dm me on discord Marci#0101

alr

**Comment by samogost** [comment]
> Marci#0101

I cant

**Comment by 6nz** [comment]
![Screenshot_2023-01-24-14-59-31-631-edit_com discord](https://user-images.githubusercontent.com/74118308/214314075-cde89196-a394-44de-a41e-28a4f7dab83f.jpg)

**Comment by 6nz** [comment]
Is that you?
